#Google Analytics
analytics-id: UA-177274313-1
  #leave blank to not use Analytics

#Subtitle
subtitle:
  active: true
  text: Tom's home on the web

#Nav 
nav:
  pages:
    active: true
  social:
    active: true

#Featured images in homepage
featured-img:
  active: true

#Show categories at the end of posts
categories:
  active: true

#Show date and read time under the post title
date-under-post:
  active: true

#Use MathJAX
mathjax:
  active: true

#Show related posts based on categories
related-posts:
  active: true
  title: "You May Also Enjoy"

#Disqus
disqus:
  disqus_shortname: "your_username" #Your disqus shortname. Leave blank to deactivate disqus comments
